version: '3'

services:
  drone-server:
    image: drone/drone:0.8.6
    ports:
      - 127.0.0.1:8000:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone
    restart: "no"
    env_file:
      - /etc/drone/server.env

  drone-agent:
    image: drone/agent:0.8.6
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    env_file:
      - /etc/drone/agent.env
